edgeproviderimage:
  repository: microsoft/iot-edge-vk-provider
  tag: latest
  pullPolicy: Always
  port: 5000
  secretsStoreName: my-secrets
  secretKey: hub0-cs
  requests:
    cpu: 10m
    memory: 120Mi
  limits:
    cpu: 100m
    memory: 250Mi
vkimage:
  repository: microsoft/virtual-kubelet
  tag: latest
  pullPolicy: Always
  requests:
    cpu: 10m
    memory: 25Mi
  limits:
    cpu: 100m
    memory: 100Mi
env:
  nodeName: iot-edge-connector-hub0
  nodeOsType: Linux
  monitoredNamespace: ""
  # 'provider' must be 'web'
  provider: web
taint:
  enabled: true
  key: virtual-kubelet.io/provider
  value: iotedge
  # 'effect' must be 'NoSchedule' or 'NoExecute'.
  effect: NoSchedule
# Install Default RBAC roles and bindings
rbac:
  install: true
  # RBAC api version (currently v1)
  apiVersion: v1
  # Cluster role reference
  roleRef: cluster-admin
