edgeproviderimage:
  repository: microsoft/iot-edge-vk-provider
  tag: latest
  pullPolicy: Always
  port: 5000
  secretsStoreName: my-secrets
  secretKey: hub0-cs
vkimage:
  repository: microsoft/virtual-kubelet
  tag: latest
  pullPolicy: Always
env:
  nodeName: iot-edge-connector-hub0
  nodeOsType: Linux
  monitoredNamespace: ""
  # 'provider' must be 'web'
  provider: web
taint:
  enabled: true
  key: virtual-kubelet.io/provider
  value: iotedge
  # 'effect' must be 'NoSchedule' or 'NoExecute'.
  effect: NoSchedule
# Install Default RBAC roles and bindings
rbac:
  install: true
  serviceAccountName: virtual-kubelet
  # RBAC api version (currently v1)
  apiVersion: v1
  # Cluster role reference
  roleRef: cluster-admin
