---
apiVersion: v1
kind: Pod
metadata:
  name: web1
  labels:
    foo: bar
spec:
  containers:
  - name: web1
    image: nginx
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  - name: edgeprov
    image: avranju/edgeprovider
    ports:
      - containerPort: 5000
    env:
      - name: HUB_CONNECTION_STRING
        value: <Hub Connection String Here>
  volumes:
    - name: config-volume
      configMap:
        name: example-config
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: example-config
data:
  example.property.1: hello
  example.property.2: world
---
