{{ if .Values.rbac.install }}
apiVersion: "rbac.authorization.k8s.io/{{ .Values.rbac.apiVersion }}"
kind: ClusterRoleBinding
metadata:
  name: {{ template "edge-provider.fullname" . }}-role-binding
subjects:
- kind: ServiceAccount
  name: {{ template "edge-provider.fullname" . }}-service-account
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.roleRef }}
{{ end }}
